name: .NET Core

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SLN_FILE: './src/NServiceBus.InMemory.sln'
  PACKAGE_LOCATION: './src/NServiceBus.Transport.InMemory/bin/Release/*.nupkg'

  CONFIGURATION: Release

  # no spam
  DOTNET_NOLOGO: true

  # notracking
  DOTNET_CLI_TELEMETRY_OPTOUT: true
