name: .NET Core

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SLN_FILE: './src/NServiceBus.Transport.InMemory.sln'
  PACKAGE_LOCATION: './src/NServiceBus.Transport.InMemory/bin/Release/*.nupkg'

  CONFIGURATION: Release

  # no spam
  DOTNET_NOLOGO: true

  # notracking
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
  ASSEMBLY_VERSION: 1.0.${{ github.run_number }}
  
jobs:

  build:
    name: Buid, Test, Pack and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/stevewgh/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      run: dotnet build ${{env.SLN_FILE}} /p:AssemblyVersion=${{env.ASSEMBLY_VERSION}} --configuration ${{env.CONFIGURATION}}

    - name: Test
      run: dotnet test ${{env.SLN_FILE}} --no-restore --no-build --verbosity normal --configuration ${{env.CONFIGURATION}}

    - name: Pack
      run: dotnet pack ${{env.SLN_FILE}} -p:PackageVersion=${{env.ASSEMBLY_VERSION}} --no-build
      
    - name: Publish to GitHub Packages
      if: github.ref != 'refs/heads/master'
      run: 
        dotnet nuget push ${{env.PACKAGE_LOCATION}} --skip-duplicate      

    - name: Publish to Nuget.org
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: 
        dotnet nuget push ${{env.PACKAGE_LOCATION}} -k ${{secrets.NUGET_ORG_API_KEY}} -s https://api.nuget.org/v3/index.json
